"""Job search."""

from __future__ import annotations

import hashlib
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session

from app.connectors.registry import source_labels
from app.db import get_db
from app.deps import require_extension_token
from app.models import Job
from app.schemas import AdhocJobIn, JobRecord, SearchQuery, SearchResponse
from app.services.search import search_jobs

router = APIRouter(prefix="/api", tags=["search"])


def _adhoc_id(company: str, title: str, apply_url: str) -> str:
    digest = hashlib.sha1(f"{company}|{title}|{apply_url}".encode()).hexdigest()[:16]
    return f"adhoc:{digest}"


@router.post(
    "/jobs/adhoc",
    response_model=JobRecord,
    dependencies=[Depends(require_extension_token)],
)
def create_adhoc_job(payload: AdhocJobIn, db: Session = Depends(get_db)) -> JobRecord:
    """Ingest a job the browser extension scraped itself — a Greenhouse/Lever/Workday
    page reached via a LinkedIn/Indeed redirect that none of our connectors indexed.

    The id is derived from (company, title, apply_url) rather than autogenerated, so
    resubmitting the same page (the extension calls this on every popup open) upserts
    the same Job row instead of piling up duplicates. Once inserted it's just another Job
    row — /api/apply/{job_id} and the cover-letter endpoint need no special-casing.
    """
    job_id = _adhoc_id(payload.company, payload.title, payload.apply_url)

    row = db.get(Job, job_id)
    if row is None:
        row = Job(id=job_id, source="adhoc")
        db.add(row)

    row.title = payload.title
    row.company = payload.company
    row.location = payload.location
    row.remote = payload.remote
    row.apply_url = payload.apply_url
    row.description = payload.description
    row.fetched_at = datetime.now(timezone.utc)

    db.commit()
    db.refresh(row)

    return JobRecord(
        id=row.id,
        source=row.source,
        title=row.title,
        company=row.company,
        location=row.location,
        remote=row.remote,
        salary_min=row.salary_min,
        salary_max=row.salary_max,
        currency=row.currency,
        posted_at=row.posted_at,
        apply_url=row.apply_url,
        description=row.description,
    )


@router.get("/search", response_model=SearchResponse)
async def search(
    q: str = Query("", description="Job title or keywords"),
    location: str = Query(""),
    remote_only: bool = Query(False),
    limit: int = Query(50, ge=1, le=200),
    db: Session = Depends(get_db),
) -> SearchResponse:
    return await search_jobs(
        db, SearchQuery(query=q, location=location, remote_only=remote_only, limit=limit)
    )


@router.get("/sources")
def sources() -> dict[str, str]:
    """Source id -> display label, for the settings screen."""
    return source_labels()
